% real/complex double version
mex CFLAGS="-fexceptions -fPIC -fno-omit-frame-pointer -pthread" ...
    COPTIMFLAGS="-march=native -msse2 -msse3 -Ofast -flto -DNDEBUG" ...
    LDOPTIMFLAGS="-Ofast -flto" ...
    infnorm_cd.c

% real/complex single version
mex CFLAGS="-fexceptions -fPIC -fno-omit-frame-pointer -pthread" ...
    COPTIMFLAGS="-march=native -msse2 -msse3 -Ofast -flto -DNDEBUG" ...
    LDOPTIMFLAGS="-Ofast -flto" ...
    infnorm_cs.c